In [229]:
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib
matplotlib.style.use('ggplot')

from __future__ import print_function
from six.moves import cPickle as pickle

from sklearn import preprocessing

data1 = pd.read_csv("AGW.csv")
data = np.genfromtxt("AIO.csv",delimiter=',')

In [230]:
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error,mean_absolute_error, r2_score

In [231]:
print(data.shape)
print("\n ")
print(data[:,0])

(8743L, 30L)

 
[ nan  nan  nan ...,  nan  nan  nan]


In [232]:
data = np.delete(data,0,1)
data = np.delete(data,0,0)
print(data.shape)
print(data[:,:])

(8742L, 29L)
[[  2.43642000e+02   2.44470000e+02  -7.00000000e-01 ...,   2.44570000e+02
   -8.15000000e-01   0.00000000e+00]
 [  2.43392000e+02   2.44108000e+02  -8.25000000e-01 ...,   2.44328000e+02
   -8.00000000e-01   1.15000000e+02]
 [  2.42803000e+02   2.43596000e+02  -9.00000000e-01 ...,   2.43825000e+02
   -8.20000000e-01   8.55310000e+01]
 ..., 
 [  2.58662000e+02   2.58563000e+02   1.25000000e-01 ...,   2.58729000e+02
    1.30000000e-01   7.13730000e+01]
 [  2.58909000e+02   2.58743000e+02   1.25000000e-01 ...,   2.58989000e+02
    1.30000000e-01   7.13690000e+01]
 [  2.58862000e+02   2.58692000e+02   1.00000000e-01 ...,   2.58995000e+02
    1.30000000e-01   7.13650000e+01]]


In [233]:
print(data[:,-1])

[   0.     115.      85.531 ...,   71.373   71.369   71.365]


In [234]:
data = np.delete(data,-1,1)

In [235]:
print(data.shape)
print(data[:,:])


(8742L, 28L)
[[  2.43642000e+02   2.44470000e+02  -7.00000000e-01 ...,   2.44060000e+02
    2.44570000e+02  -8.15000000e-01]
 [  2.43392000e+02   2.44108000e+02  -8.25000000e-01 ...,   2.43822000e+02
    2.44328000e+02  -8.00000000e-01]
 [  2.42803000e+02   2.43596000e+02  -9.00000000e-01 ...,   2.43400000e+02
    2.43825000e+02  -8.20000000e-01]
 ..., 
 [  2.58662000e+02   2.58563000e+02   1.25000000e-01 ...,   2.58447000e+02
    2.58729000e+02   1.30000000e-01]
 [  2.58909000e+02   2.58743000e+02   1.25000000e-01 ...,   2.58705000e+02
    2.58989000e+02   1.30000000e-01]
 [  2.58862000e+02   2.58692000e+02   1.00000000e-01 ...,   2.58655000e+02
    2.58995000e+02   1.30000000e-01]]


In [236]:
fv = data[:,-1]

In [237]:
fv

array([-0.815, -0.8  , -0.82 , ...,  0.13 ,  0.13 ,  0.13 ])

In [238]:
n = pd.rolling_mean(data[:,2],5)
ma10 = pd.rolling_mean(data[:,2],30)

C:\Users\Jatin\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: pd.rolling_mean is deprecated for ndarrays and will be removed in a future version
  """Entry point for launching an IPython kernel.
C:\Users\Jatin\Anaconda2\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: pd.rolling_mean is deprecated for ndarrays and will be removed in a future version
  


In [239]:
n[0:5] =data[0:5,2]
ma10[0:30] =data[0:30,2]

In [240]:
X = np.vstack((n,data[:,2]))

In [241]:
X.shape

(2L, 8742L)

In [242]:
X = np.transpose(X)
print(X.shape)
print(fv.shape)

(8742L, 2L)
(8742L,)


In [156]:
X = np.hstack((X, data[:,0:2]))

In [221]:
X.shape

(8742L, 2L)

In [243]:
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(X, fv)

# Make predictions using the testing set
pred = regr.predict(X)
print('Coefficients: \n', regr.coef_)

Coefficients: 
 [ 0.49980648  0.49083167]


In [244]:
print("Mean squared error: %.6f"
      % mean_squared_error(fv, pred))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(fv, pred))

Mean squared error: 0.004372
Variance score: 0.98


In [245]:
pred[-20:]

array([ 0.12815832,  0.1011177 ,  0.1479262 ,  0.14315251,  0.13815444,
        0.19723374,  0.09406934,  0.14065348,  0.14065348,  0.11111383,
        0.11088946,  0.11838656,  0.08634788,  0.13793007,  0.11588752,
        0.14542717,  0.12088559,  0.12588365,  0.12088559,  0.10611576])

In [246]:
fv[-20:]

array([ 0.165,  0.155,  0.15 ,  0.15 ,  0.14 ,  0.115,  0.13 ,  0.115,
        0.12 ,  0.125,  0.135,  0.135,  0.145,  0.135,  0.13 ,  0.13 ,
        0.13 ,  0.13 ,  0.13 ,  0.13 ])

In [247]:
print('Coefficients: \n', regr.intercept_)
print('Coefficients: \n', regr.coef_)

Coefficients: 
 -0.0079422442614
Coefficients: 
 [ 0.49980648  0.49083167]


In [228]:
np.matmul(X,regr.coef_)

array([-0.68491253, -0.80721833, -0.85614066, ...,  0.07338348,
        0.08976661,  0.1171475 ])